- src/renderer/components/App/App.css
The list numbers were not showing up in the assistant response, this fixes that.
> Fix the list rendering

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- CONTRIBUTING.md
- README.md
> Readme Updated

- README.md
> Update user README

- README.md
- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
- src/renderer/components/SettingsPanel/SettingsPanel.tsx
Please include a summary of the change and which issue is fixed. Include relevant motivation and context.
> bump version to v0.0.2

- README.md
- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
- src/renderer/components/SettingsPanel/SettingsPanel.tsx
Please include a summary of the change and which issue is fixed. Include relevant motivation and context.
> Ga/release 0.0.2

- release/app/package.json
Please include a summary of the change and which issue is fixed. Include relevant motivation and context.
> release app description shows up on task manager

- src/cobolt-backend/connectors/mcp_client.ts
- src/cobolt-backend/connectors/mcp_tools.ts
- src/cobolt-backend/utils/error_manager.ts
- src/main/main.ts
- src/main/preload.ts
- src/renderer/components/App/App.tsx
- src/renderer/components/ErrorDialog/ErrorDialog.css
- src/renderer/components/ErrorDialog/ErrorDialog.tsx
- src/renderer/components/SettingsPanel/SettingsPanel.css
- src/renderer/components/SettingsPanel/SettingsPanel.tsx
- src/renderer/preload.d.ts
- tests/__tests__/App/App.test.tsx
- tests/__tests__/ErrorDialog/ErrorDialog.test.tsx
- tests/__tests__/cobolt-backend/connectors/mcp_client.test.ts
Error dialog for Startup Errors or MCP Errors
Dialog Screenshot:
MCP Config Error:
MCP Server Error:
Fixes # (issue number): #24 
Run the application
> Error dialog for Startup Errors or MCP Errors

- .github/workflows/publish.yml
- .github/workflows/test.yml
- package.json
Mac app is now signed and notarized
> Mac signing and notarization

- README.md
> fix path to sample MCP server

- src/cobolt-backend/prompt_templates.ts
added JSDoc comments and usage examples to all exported functions in [prompt_templates.ts](vscode-file://vscode-app/c:/Users/USER/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html). This should improves the code readability, help contributors understand the codebase.
> docs: add JSDoc on prompt_template.ts

- .github/workflows/publish.yml
This fixes the windows publish job
Tested on windows by downloading and installing the exe
> Add windows job

- src/cobolt-backend/ollama_client.ts
- src/main/main.ts
- src/renderer/components/ErrorDialog/ErrorDialog.css
- src/renderer/components/ErrorDialog/ErrorDialog.tsx
Models are being downloaded when we open the app for the first time (not during initial setup). This leads to a large time period where nothing shows up on the screen even thought the app is running in the backgrond.
Showing a dialog: 
[Note: The outside box is also the same color of green, it just messes up when I take a screenshot]
When we use an incorrect model in the config: 
Fixes # (issue number) : https://github.com/platinum-hill/cobolt/issues/40
Test 1:
Delete llama3.1:8b from ollama
Open app
Test 2:
Deleted both models and tested that it worked fine with both.
> Add Dialog Box for Model Download

- .github/ISSUE_TEMPLATE/bug_report.md
- README.md
Update Readme that winget is required for Windows. 
Update the Issue Template to attach logs so it is easy to debug issues.
Fixes # (issue number) : https://github.com/platinum-hill/cobolt/issues/46
N/A
> docs: Readme Windows winget addition and Add logs section in Issue Template

- src/renderer/components/ChatInterface/ChatInterface.css
- src/renderer/components/ChatInterface/ChatInterface.tsx
Adds support for reasoning models
> feat: support for reasoning models

- .github/pull_request_template.md
- README.md
- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
> chore: bump to 0.0.5

- src/cobolt-backend/ollama_client.ts
Adding more logs so we can figure out why ollama failed to start
Not required
Not applicable
> fix: add logs when starting/stopping ollama

- README.md
- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
> bump to 0.0.6

- src/cobolt-backend/ollama_client.ts
- src/main/setup.ts
fix: linux ollama setup and ollama start command 
> fix: linux ollama setup and ollama start command 

- src/cobolt-backend/memory.ts
- src/cobolt-backend/ollama_client.ts
- src/cobolt-backend/query_engine.ts
- src/main/main.ts
- src/renderer/components/ChatInterface/ChatInterface.css
- src/renderer/components/ChatInterface/ChatInterface.tsx
This reverts commit e15085ae66828e78014afb4f1ab372b9259b8c2d.
> Revert "Feature: Sequential streamed tool calling (#66)"

- src/main/menu.ts
Small PR to update the help menu to point to Cobolt docs and issues
- [ X] Bug fix (non-breaking change which fixes an issue)
Tested help menu links on windows
- [ x] My code follows the style guidelines of this project
- [ x] My changes generate no new warnings
- [ x] I have tested the app on Windows (If not, leave unchecked so we can test before merging)
> Updated windows help menu links
